### PR TITLE
InternalIPKernel: fix ResourceWarnings from unclosed pipes.

### PR DESCRIPTION
**Pull request by mdickinson**
The consoles created by `InternalIPKernel.new_qt_console` are `subprocess.Popen` instances created with `stderr=PIPE` and `stdout=PIPE`. We kill those subprocesses at shutdown time, but don't close the pipes. This leads to `ResourceWarning`s (at least in Python 3) from code using this.

This PR explicitly closes the pipes.

### CODE REVIEW

**Comment by rahulporuri** [comment]
It looks like we are closing stdout/stderr pipes in the `shutdown` method of the kernel. after we call `cleanup_consoles` - 

 https://github.com/enthought/envisage/blob/072b8457352e8c88e788a789f93653120422be80/envisage/plugins/ipython_kernel/internal_ipkernel.py#L118-L130 

Can I ask why we have to close the stderr/stdout pipes on each console individually and additionally on the `InternalIPKernel` ?

**Comment by mdickinson** [comment]
> Can I ask why we have to close the stderr/stdout pipes on each console individually and additionally on the `InternalIPKernel` ?

Those are different streams. The stderr and stdout pipes that are being closed here are used for communication between the child process (the qt console) and the main process (running the IPython kernel). That's unrelated to changes to the main process stderr and stdout.

**Comment by rahulporuri** [comment]
LGTM

**Comment by mdickinson** [comment]
Thanks for reviewing!

**Pull request merged**
