### PR TITLE
Remove old ipython_shell plugin (based on outdated technology)

### PR DESCRIPTION
**Pull request by mdickinson**
This PR removes the old `IPythonShell` plugin. This plugin is based on a pre-IPython 1.0 version, and uses the workbench technology (which has long since been superseded by tasks).

cf: #172 

Note: the `IPythonPlugin` provided an IPython-based kernel and front end. For the kernel, similar functionality is present in the `envisage.plugins.ipython_kernel` plugins. There's no immediate replacement for the view, but we have projects based on Canopy Data with qtconsole-based views that could be contributed back to Envisage.

### CODE REVIEW

**Comment by prabhuramachandran** [comment]
Just a data point, Mayavi still uses the workbench plugins (for the application), although it doesn't use the IPython shell.  I would love to rework the application to use tasks but that does seem like it would be a non-trivial code change.  I just haven't had the time to do this but if you are looking to remove the workbench, it would be good to have a timeline before it disappears so I can make sure that Mayavi is also ported to tasks (and is that what I should do?).

**Comment by mdickinson** [comment]
Right; I'm aware that Mayavi is still using the workbench stuff, and have no plans to remove it immediately. (And that would happen mostly in PyFace, anyway.)

But this plugin is well and truly broken: to use it, you have to be on pre-1.0.0 IPython. And I suspect that the set of people who want to use pre-1.0.0 IPython in combination with the latest and greatest Envisage is going to be ... small.

**Comment by prabhuramachandran** [comment]
Oh sorry I did not mean to block this PR, just wanted to make sure that workbench isn't disappearing. :)

**Comment by corranwebster** [comment]
For the record, as long as Mayavi uses Workbench, it's not disappearing.  I would like to move it to Apptools, however.

**Comment by mdickinson** [comment]
@rahulporuri 

> do you think it will be useful to add a description of the `IPythonShell` plugin in the PR

Done! Thanks for the review.

**Pull request merged**
