### PR TITLE
Experiment with aws cpu and virtualization in travis CI

### LINKED ISSUE #350: Experiment with aws cpu and and virtualization in travis CI
ref : https://blog.travis-ci.com/2020-09-11-arm-on-aws

There is a new type of CPI available on travis CI com and a new type of virtualization - both of these put together apparently provide a meaningful speedup in travis-ci.com CI jobs. Now that envisage CI has been moved over from travis-ci.org to travis-ci.com, we can experiment with these variables to see if we see a meaningful speedup.

### PR DESCRIPTION
**Pull request by aaronayres35**
closes #350

### CODE REVIEW

**Comment by aaronayres35** [comment]
on the empty commit (pre-experimentation with new cpu/virtualization) travis CI succeeded in 6m 35s

**Comment by aaronayres35** [comment]
travis build has been started 51 min ago.
Not sure where this delay is coming from

**Comment by rahulporuri** [comment]
travis linux is failing with the following message `"Automatic restarts limited: Please try restarting this job later or contact support@travis-ci.com."` and it looks like the cpu is only available on linux (https://travis-ci.com/github/enthought/envisage/builds/193741909)

**Comment by rahulporuri** [comment]
also. it looks like you're missing a `group: edge` tag, which is why the linux jobs might be failing - https://blog.travis-ci.com/2020-09-11-arm-on-aws.

**Comment by aaronayres35** [comment]
> also. it looks like you're missing a `group: edge` tag, which is why the linux jobs might be failing - https://blog.travis-ci.com/2020-09-11-arm-on-aws.

I looked through the changelog at https://changelog.travis-ci.com/ and they had a post that said:
"
Bionic and Xenial images promoted to the stable channel
Following the announcements from two weeks ago (Xenial and Bionic), we're promoting the updated images to the stable channel. That means you don't have to include the tag group: edge in your .travis.yml file anymore to use the updated build environments.

For any issues, please e-mail us at support@travis-ci.com. If you need more information, check out our docs.
"

**Comment by kitchoi** [comment]
The objective of #350 is to experiment with the AWS CPU. Is the objective fulfilled? Or are there still more things to try?

**Comment by aaronayres35** [comment]
> The objective of #350 is to experiment with the AWS CPU. Is the objective fulfilled? Or are there still more things to try?

It has been a while since I looked at this, but I don't think it was ever fully seen through.  I never understood what was causing the `"Automatic restarts limited: Please try restarting this job later or contact support@travis-ci.com."` failure, and so was never able to do a good comparison of how the CPU change affected test time.

**Comment by rahulporuri** [comment]
I think we can just close this PR and move on now. We intend to ditch Travis CI in favor of GitHub Actions in the near future anyway.

**Pull request closed without merging**
