### PR TITLE
Stop using Appveyor CI

### PR DESCRIPTION
**Pull request by rahulporuri**
This PR removes the appveyor configuration file and related utilities used by the appveyor CI.
This PR also removes a number of scripts which were used to install edm on various platforms.

This PR is one step towards enthought/ets#63

### CODE REVIEW

**Comment by rahulporuri** [comment]
Note that I updated the branch protection settings in this repository to remove "Appveyor CI" as a required check and instead include the GitHub Actions CI checks as required.

**Comment by mdickinson** [comment]
LGTM

**Comment by mdickinson** [comment]
LGTM

**Review by mdickinson — APPROVED** [review]

**Comment by mdickinson** [comment]
@rahulporuri I assume you also set the "Skip branches without appveyor.yml" setting in the Appveyor project config? (If you didn't just do that, then I wonder why Appveyor tried to execute a build.)

**Comment by rahulporuri** [comment]
> @rahulporuri I assume you also set the "Skip branches without appveyor.yml" setting in the Appveyor project config? (If you didn't just do that, then I wonder why Appveyor tried to execute a build.)

Ahh. nice catch. I didn't do that. I just did though - for all ETS projects.

**Comment by rahulporuri** [comment]
Thanks for the review @mdickinson . I'm going to ignore the failed Appveyor build (duh) and merge this PR.

**Comment by rahulporuri** [comment]
Note that i've removed the Travis and Appveyor CI webhooks from this repository

**Pull request merged**
