### PR TITLE
Experiment: include pyqt5 and pyside2 in CI runs

### PR DESCRIPTION
**Pull request by mdickinson**
Experimental PR to see just how bad the CI failures are if we try to include pyqt5 and pyside2.

In the unlikely event that the CI run passes, I'll merge this PR. (I might ask for a re-run first, just to be sure.)

### CODE REVIEW

**Comment by mdickinson** [comment]
Windows failures on all Python versions, resembling the following:
```
======================================================================
ERROR: Failure: RuntimeError (No pyface.toolkits plugin could be loaded for qt4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\appveyor\.edm\envs\envisage-test-3.6-pyside2\lib\site-packages\nose\failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "C:\Users\appveyor\.edm\envs\envisage-test-3.6-pyside2\lib\site-packages\nose\loader.py", line 419, in loadTestsFromName
    addr.filename, addr.module)
  File "C:\Users\appveyor\.edm\envs\envisage-test-3.6-pyside2\lib\site-packages\nose\importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "C:\Users\appveyor\.edm\envs\envisage-test-3.6-pyside2\lib\site-packages\nose\importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "C:\Users\appveyor\.edm\envs\envisage-test-3.6-pyside2\lib\imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "C:\Users\appveyor\.edm\envs\envisage-test-3.6-pyside2\lib\imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 675, in _load
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "C:\Users\appveyor\.edm\envs\envisage-test-3.6-pyside2\lib\site-packages\envisage\ui\action\tests\action_manager_builder_test_case.py", line 4, in <module>
    from pyface.api import GUI  # noqa
  File "C:\Users\appveyor\.edm\envs\envisage-test-3.6-pyside2\lib\site-packages\pyface\api.py", line 17, in <module>
    from .about_dialog import AboutDialog
  File "C:\Users\appveyor\.edm\envs\envisage-test-3.6-pyside2\lib\site-packages\pyface\about_dialog.py", line 19, in <module>
    from .toolkit import toolkit_object
  File "C:\Users\appveyor\.edm\envs\envisage-test-3.6-pyside2\lib\site-packages\pyface\toolkit.py", line 27, in <module>
    toolkit = toolkit_object = find_toolkit('pyface.toolkits')
  File "C:\Users\appveyor\.edm\envs\envisage-test-3.6-pyside2\lib\site-packages\pyface\base_toolkit.py", line 263, in find_toolkit
    return import_toolkit(ETSConfig.toolkit, entry_point)
  File "C:\Users\appveyor\.edm\envs\envisage-test-3.6-pyside2\lib\site-packages\pyface\base_toolkit.py", line 227, in import_toolkit
    raise RuntimeError(msg)
RuntimeError: No pyface.toolkits plugin could be loaded for qt4
```

My understanding is that PyFace master would likely fix this.

**Comment by rahulporuri** [comment]
@mdickinson now that we have a new release for pyface, do you want to update this PR and re-run CI?

**Comment by mdickinson** [comment]
> do you want to update this PR and re-run CI?

Good idea. Done.

**Comment by mdickinson** [comment]
Windows builds all still failing;  failing on Python 2 because there's no PySide2 wheel available from PyPI for Windows / Python 2.7.

Failing on Python 3 for the same reasons as before (RuntimeError: No pyface.toolkits plugin could be loaded for qt4)

**Comment by mdickinson** [comment]
I'm a bit baffled by the failures. I can reproduce locally: if I do
```
python etstool.py test --runtime 3.6 --toolkit pyside2
```
then I get the failure.

But if I run with:
```
edm run -e envisage-test-3.6-pyside2 -- coverage run -p -m nose.core -v envisage --nologcapture
```
then there's no failure.

Possible difference in environment variables?

**Comment by mdickinson** [comment]
There's a DLL load failure for PySide2 / Windows / Python 3.x; we're seeing the same issues on the PyFace CI.

Trying with the latest PySide2, just for fun.

**Comment by mdickinson** [comment]
Looks like PySide2 isn't an option, for the moment. We probably want to revisit once we have PySide2 eggs in the buildsystem (should that ever happen).

**Comment by mdickinson** [comment]
I'm going to close this PR.

**Pull request closed without merging**
