### PR TITLE
Include lazy defaults in query evaluation for get_service(s)

### LINKED ISSUE #140: query evaluation in get_service(s) omits lazy population of default traits
Here is one example to reproduce the bug:

```
from envisage.api import Application
from traits.api import Interface, provides, HasTraits, Str, Int, HasStrictTraits


class IPlumber(Interface):
    """ What plumbers do! """

    # The plumber's name.
    name = Str

    # The plumber's location.
    location = Str

    # The price per hour (in say, Estonian Krooni ;^)
    price = Int

    def fix_leaking_pipe(self, pipe):
        """ Fix a leaking pipe! """

@provides(IPlumber)
class Plumber(HasTraits):
    """ An actual plumber implementation! """

    # The plumber's name.
    name = Str

    # The plumber's location.
    location = Str

    # The price per hour (in say, Estonian Krooni ;^)
    price = Int

    def fix_leaking_pipe(self, pipe):
        """ Fix a leaking pipe! """
        print('fixed!')


@provides(IPlumber)
class Foo(HasTraits):
    foo = Int
    price = Int(20)


if __name__ == '__main__':
    application = Application()
    fred = Plumber()
    foo = Foo()
    fred_id = application.register_service(IPlumber, fred)
    foo_id = application.register_service(IPlumber, foo)

    obj = application.get_services(IPlumber, 'price<30')

    print(obj)
```

and the problematic code: https://github.com/enthought/envisage/blob/57338fcb0ea69c75bc3c86de18a5967d8e78c6c1/envisage/service_registry.py#L191-L198

### PR DESCRIPTION
**Pull request by aaronayres35**
closes #140 

This PR goes through the editable_traits on a service and access them.  This forces lazy defaults to be evaluated so that they end up in the service's `__dict__` which is then used in the namespace for making queries.

### CODE REVIEW

**Review by corranwebster — APPROVED** [review]
This looks like a reasonable fix.  Don't know if this is still an important issue.

**Comment by mdickinson** [comment]
I don't think this is the way we want to go: accessing those traits may have unintended side-effects, or take a long time computationally.

I think we want something more dynamic here, where only the traits mentioned in a property are accessed; that would obviously require a bit more work to implement. Ideally, we'd find a solution that avoids the need for `eval` altogether, either by restricting the allowed expressions and parsing them ourselves, or by using a general selection callable instead of evaluating a string.

**Comment by mdickinson** [comment]
@aaronayres35 Do you still have a need for the associated issue to be solved? If so, we can look into other possible solutions; if not, I'll close this PR (but leave the issue open, of course).

**Comment by aaronayres35** [comment]
> @aaronayres35 Do you still have a need for the associated issue to be solved? If so, we can look into other possible solutions; if not, I'll close this PR (but leave the issue open, of course).

No, no need.  Feel free to close

**Comment by mdickinson** [comment]
Thanks, @aaronayres35. Closing.

**Pull request closed without merging**
