### PR TITLE
Compatibility fixes for ipykernel 6

### PR DESCRIPTION
**Pull request by mdickinson**
This PR contains some minor compatibility fixes for ipykernel versions 6.0.0 and later. There's still significant work to do before we have full compatibility - this is really just clearing away some of the weeds so that we can see the real issues.

Details

- We use `capture_fd_output=False` when creating the `IPKernelApp`. This prevents the kernel application from setting up threads for stdout and stderr redirection. Those threads have been causing shutdown issues.
- In `log_connection_info`, we set either the `_ports` traitlet or the `ports` traitlet; whichever works first (this trait was renamed at some point in the ipykernel history)
- We retrieve the history manager earlier so that we can shut its bits down - the new `ipykernel` sets the history manager trait to `None` when `atexit_operations` is called, so that we can no longer retrieve the history manager _after_ calling `atexit_operations`.
- the most recent `IPython` has deleted the `IPython.utils.io.stdout` and `IPython.utils.io.stderr` attributes; update our cleanup code to allow for this case

Related upstream issues:
- https://github.com/ipython/ipykernel/issues/867
- https://github.com/ipython/ipykernel/issues/868

### CODE REVIEW

**Comment by mdickinson** [comment]
This PR is ready for review.

**Review by corranwebster — APPROVED** [review]
LGTM

**Comment by corranwebster** [comment]
One additional question - does this need any changes to the setup.py optional dependencies for ipython?

**Comment by mdickinson** [comment]
> does this need any changes to the setup.py optional dependencies for ipython

Unfortunately not: it moves us a bit towards being able to relax the current version constraints, but we don't get all the way there.

**Pull request merged**
