### PR TITLE
Update gh-pages documentation to include API documentation.

### PR DESCRIPTION
**Pull request by mdickinson**
This PR updates the online documentation to include generated API documentation.

### CODE REVIEW

**Comment by mdickinson** [comment]
Self-review: this looks fine to me from a quick eyeball of the changes: lots of new things added, nothing deleted, nothing that already exists substantially changed. I'll merge shortly.

**Comment by rahulporuri** [comment]
Eek. I thought this PR added infrastructure to build API docs (which I now remember was done earlier).

**Comment by mdickinson** [comment]
Yeah, the doc-building infrastructure is already there. This PR just replaces the existing gh-pages content with the new content (as autogenerated with `python etstool.py docs`).

**Comment by mdickinson** [comment]
Self-merging (evil laugh). Post-merge reviews welcome. Go to http://docs.enthought.com/envisage/ to browse the updated documentation.

**Pull request merged**
