### PR TITLE
Include license, readme and changelog files in the source distribution.

### LINKED ISSUE #106: PyPI: Missing license file
The [source package on PyPI](https://pypi.io/packages/source/e/envisage/envisage-4.6.0.tar.gz) is missing the LICENSE.txt file

### PR DESCRIPTION
**Pull request by mdickinson**
Fixes #106 by adding `LICENSE.txt`, `README.rst`, `CHANGES.txt` and related files to the manifest.

### CODE REVIEW

**Comment by mdickinson** [comment]
I've tested by building an sdist and verifying that it contains the listed files.

**Comment by cfarrow** [comment]
Is it common to list `MANIFEST.in` in `MANIFEST.in`. I've probably seen this before, but never noticed.

In any case, LGTM.

**Comment by mdickinson** [comment]
I don't know about common, but we do it for Traits UI and Traits. It means that the source distribution can be used as a basis for development. (It's not clear to me who might want to create a source distribution from a source distribution, but if they wanted to, then they could ...)

**Comment by corranwebster** [comment]
I think there are other things that should either be in the `MANIFEST.in` or the `setup.py`.  For example, we arw including the image licenses, but are we including the images, eg. here https://github.com/enthought/envisage/tree/38c1ffc40cdd0b9a2e19faed80c8f253a08c553c/envisage/plugins/remote_editor/editor_plugins/editra/images

**Comment by dpinte** [comment]
Can we get this merged in the coming day or two?

**Comment by mdickinson** [comment]
> Can we get this merged in the coming day or two?

I don't have bandwidth to work on it in the next couple of days. If someone else wants to take over the PR, I'm fine with that.

**Comment by rahulporuri** [comment]
>  For example, we are including the image licenses, but are we including the images

All of the images and the image licenses are being included in the sdist. the `package_data` kwarg in the setup script is taking care of all `images/*`. 

We might want to consider removing the use of `package_data` and moving over the relevant information into the manifest file.

Here are the items currently not included in the sdist (generated from this branch) - 

- [ ] DESIGN.txt, README.txt and TODO.txt in https://github.com/enthought/envisage/tree/master/envisage/ui/single_project 
- [ ] `emacs` editor plugin - https://github.com/enthought/envisage/tree/master/envisage/plugins/remote_editor/editor_plugins/emacs 

Should they be included in the sdist/pkg?

**Comment by mdickinson** [comment]
> We might want to consider removing the use of `package_data` and moving over the relevant information into the manifest file.

Note that there are two different needs here: building source distributions, and building eggs. By default, the manifest file is just for source distributions. If you remove `package_data`, then built eggs will be missing necessary package data. You can fix that by supplying `include_package_data=True` to the `setup` function, and then data files within the packages that also occur in MANIFEST.in are automatically included. But that might not be exactly what we want here.

**Comment by mdickinson** [comment]
Here's the difference I see between the repository and the generated sdist:
```
mirzakhani:Desktop mdickinson$ diff -qtr envisage envisage-4.8.0.dev63
Only in envisage: .coveragerc
Only in envisage: .git
Only in envisage: .gitignore
Only in envisage: .travis.yml
Only in envisage-4.8.0.dev63: PKG-INFO
Only in envisage: appveyor-clean-cache.txt
Only in envisage: appveyor-run.cmd
Only in envisage: appveyor.yml
Only in envisage: ci-src-requirements.txt
Only in envisage: docs
Only in envisage-4.8.0.dev63/envisage: _version.py
Only in envisage/envisage/plugins/remote_editor/editor_plugins: emacs
Only in envisage/envisage/plugins/remote_editor/editor_plugins: readme.txt
Only in envisage/envisage/tests/bad_eggs: acme.bad
Only in envisage/envisage/tests/eggs: acme.bar
Only in envisage/envisage/tests/eggs: acme.baz
Only in envisage/envisage/tests/eggs: acme.foo
Only in envisage/envisage/ui/single_project: DESIGN.txt
Only in envisage/envisage/ui/single_project: README.txt
Only in envisage/envisage/ui/single_project: TODO.txt
Only in envisage-4.8.0.dev63: envisage.egg-info
Only in envisage: etstool.py
Only in envisage: examples
Only in envisage: install-edm-linux.sh
Only in envisage: install-edm-osx.sh
Only in envisage: install-edm-windows.cmd
Only in envisage-4.8.0.dev63: setup.cfg
Only in envisage: tox.ini
```

**Comment by mdickinson** [comment]
> * DESIGN.txt, README.txt and TODO.txt

Let's include these; it's easy to do. I'll fix this shortly.

> emacs editor plugin

I'm finding it hard to care about this; I very much doubt that anyone is using it. I notice that there's an `editra` plugin that _is_ being picked up, because it has a package structure, while the `emacs` directory doesn't have an `__init__.py`. I'll add this anyway, for completeness.

**Comment by mdickinson** [comment]
Okay, here's the new diff:
```
mirzakhani:Desktop mdickinson$ diff -qtr envisage envisage-4.8.0.dev64 | sort
Only in envisage-4.8.0.dev64/envisage: _version.py
Only in envisage-4.8.0.dev64: PKG-INFO
Only in envisage-4.8.0.dev64: envisage.egg-info
Only in envisage-4.8.0.dev64: setup.cfg
Only in envisage/envisage/tests/bad_eggs: acme.bad
Only in envisage/envisage/tests/eggs: acme.bar
Only in envisage/envisage/tests/eggs: acme.baz
Only in envisage/envisage/tests/eggs: acme.foo
Only in envisage: .coveragerc
Only in envisage: .git
Only in envisage: .gitignore
Only in envisage: .travis.yml
Only in envisage: appveyor-clean-cache.txt
Only in envisage: appveyor-run.cmd
Only in envisage: appveyor.yml
Only in envisage: ci-src-requirements.txt
Only in envisage: docs
Only in envisage: etstool.py
Only in envisage: examples
Only in envisage: install-edm-linux.sh
Only in envisage: install-edm-osx.sh
Only in envisage: install-edm-windows.cmd
Only in envisage: tox.ini
```

IMO, this should be good enough, especially given the scope of the original issue. @corranwebster?

**Pull request merged**
