### PR TITLE
DEV: Update sphinx configuration to avoid execfile on file with relative import

### PR DESCRIPTION
**Pull request by cfarrow**
The docs now build.

### CODE REVIEW

**Comment by mdickinson** [comment]
Shouldn't we be avoiding `execfile` altogether, given that it doesn't exist in Python 3?

**Comment by cfarrow** [comment]
Based on that comment, which I totally knew about before you mentioned it by the way, then we should be avoiding it. I'll look at our other packages to see how we handle that.

**Comment by pankajp** [comment]
2to3 converts it to:
```
-execfile(foo)
+exec(compile(open(foo).read(), foo, 'exec'))
```

**Comment by mdickinson** [comment]
It probably doesn't matter that much: one day we may want to be able to run the doc build using Python 3, but that's orthogonal to the issue of getting the doc build up and running again at all. I think it's fine to merge this as-is, and figure out how to deal with `execfile` later.

**Comment by cfarrow** [comment]
I made the change anyway. Python 3 is here.

**Comment by mdickinson** [comment]
LGTM. Merging.

**Pull request merged**
