### PR TITLE
Test against traits 5.0.0

### PR DESCRIPTION
**Pull request by rahulporuri**
and force the installation of source deps

Closing this PR as it's main intent should've been to simply test envisage against the released version of traits (5.0.0). Given that the changes this PR introduces will need to be undone as soon as traits is available via edm, this PR can be closed.

It served it's purpose of testing envisage against traits 5.0.0

### CODE REVIEW

**Comment by rahulporuri** [comment]
I'd like to make one more change in this PR. I think we need to specify the version of `traits` that's acceptable with this envisage.

https://github.com/enthought/envisage/blob/f14c2d1ab95677a7ccc63667757c1bf44c852602/envisage/__init__.py#L6-L9

**Comment by mdickinson** [comment]
> I'd like to make one more change in this PR.

Sounds good to me. But is this so urgent that we can't wait for official Traits eggs available via EDM?

**Comment by rahulporuri** [comment]
> Sounds good to me. But is this so urgent that we can't wait for official Traits eggs available via EDM?

the pypi package still needs this specification, doesn't it?

**Comment by mdickinson** [comment]
> the pypi package still needs this specification, doesn't it?

I'm not sure what you mean. My point was that if we can wait for the EDM eggs, there's actually nothing we need to do here. `etstool.py` will automatically pick up the latest Traits once it's released.

**Comment by rahulporuri** [comment]
@mdickinson i reverted the commit https://github.com/enthought/envisage/pull/125/commits/18bac29c2352a5a3a05bc38fefd5042fe8c1fae1 which i added after you reviewed/approved this PR. Can you re-approve this PR?

**Pull request closed without merging**
