### PR TITLE
Backport fixes from master for 4.7.2 release

### PR DESCRIPTION
**Pull request by mdickinson**
- Backport commits from the following PRs to the release/4.7.x branch: #130, #136, #144, #146, #147
- Update the changelog for the release.

### CODE REVIEW

**Comment by mdickinson** [comment]
Somewhat random failure on Appveyor / Python 3.5, unrelated to actual Envisage content. Restarting to see if it persists.

**Comment by corranwebster** [comment]
Might want to set the release flag to False in this PR?

**Comment by mdickinson** [comment]
> Might want to set the release flag to False in this PR?

To be honest, I don't think it's worth it. It's only an issue if people are building releases from random points in the release/4.7.x branch, and that seems unlikely.

**Comment by mdickinson** [comment]
> To be honest, I don't think it's worth it.

But my guilty conscience forced me to do it anyway ....

Done.

**Pull request merged**
