### PR TITLE
Handle case where event.index is None

### PR DESCRIPTION
**Pull request by sjagoe**
@corranwebster 

From enthought/traits#115:
- https://github.com/enthought/traits/blob/9e5741bf49943dd37a863d15cdaef32a32cd22cc/traits/trait_handlers.py#L2552
- https://github.com/enthought/traits/blob/9e5741bf49943dd37a863d15cdaef32a32cd22cc/traits/trait_handlers.py#L2495

### CODE REVIEW

**Comment by sjagoe** [comment]
This is in fact caused by a bug in traits due to Python 3 port. Prior to that, the event index would have been `0` rather than `None`.

**Comment by mdickinson** [comment]
@sjagoe:

> This is in fact caused by a bug in traits due to Python 3 port.

Is there an open issue in the Traits tracker? If so, please could you add a comment referring to that issue?

**Comment by mdickinson** [comment]
> Is there an open issue in the Traits tracker?

Looks like https://github.com/enthought/traits/issues/334

**Comment by dpinte** [comment]
@mdickinson I've added a reference to the trais issue. If Travis-CI is green, I'll merge.

**Comment by mdickinson** [comment]
@dpinte: SGTM. Thanks.

**Pull request merged**
