### PR TITLE
Remove the categories extension point

### LINKED ISSUE #180: Remove envisage.categories extension point
A future version of Traits is likely to remove support for categories. At that point, we should remove the `envisage.categories` extension point from the core plugin.

This should likely be part of a post-2019 Python 3-only Envisage release, with a major version number bump.

### PR DESCRIPTION
**Pull request by mdickinson**
Traits categories are gone in Traits 6.0.0. This PR removes the corresponding categories extension point from the `CorePlugin`, along with supporting machinery.

Closes #180

### CODE REVIEW

**Comment by rahulporuri** [comment]
The only remaining references to category/categories in this branch are related to the preferences category/categories or general uses of the word "category".

I can't find any mention of the removed extension point or the relevant classes/functionality in the documentation - except for in the API docs which are autogenerated.

**Comment by rahulporuri** [comment]
Also, can you open an issue regarding the deprecating the `class_load_hooks` extension point (and related machinery) that we discussed offline?

**Comment by mdickinson** [comment]
> Also, can you open an issue regarding the deprecating the `class_load_hooks`

Done in #244

**Comment by mdickinson** [comment]
> I can't find any mention of the removed extension point or the relevant classes/functionality in the documentation - except for in the API docs which are autogenerated.

I can't tell whether you think this is a good thing or a bad thing. :-)

I'm happy for the 5.0.0 release to only mention this extension point in the changelog.

**Pull request merged**
