### PR TITLE
Skip tests for recent ipykernel, and add check for IPython version

### LINKED ISSUE #456: Make sure test suite passes when ipykernel >= 6 is installed
[From #448]

The IPython-related portions of Envisage currently require ipykernel < 6; changing that requires substantial effort.

To avoid this limitation holding back other users of Envisage who aren't interested in the IPython compatibility, we should ensure that Envisage and its test suite continue to function in an environment where ipykernel >= 6 is installed. In such an environment, functionality related to IPython should be disabled, and tests for that functionality should be skipped.

### PR DESCRIPTION
**Pull request by mdickinson**
This PR:

- raises `ImportError` when attempting to import IPython-related machinery if `ipykernel` version 6 or later is installed or `IPython` version 8 or later is installed
- skips IPython-related tests when run in an environment containing either `ipykernel` version 6 or later or `IPython` version 8 or later

Closes #456.

Note: PR was updated to also check the version of IPython: it turns out that IPython >= 8 is also problematic. I've updated the description above.

### CODE REVIEW

**Review by rahulporuri — APPROVED** [review]

**Comment by mdickinson** [comment]
It looks as though the IPython-related failures are occurring in spite of the `ipykernel < 6` restriction. It seems likely that that  restriction is not enough.

Comparison of installed packages between the last successful run of the `Test with PyPI` workflow and the above one:

Last successful run:
```
Successfully installed apptools-5.1.0 backcall-0.2.0 configobj-5.0.6 decorator-5.1.0 entrypoints-0.3 envisage-6.1.0.dev1 importlib-metadata-4.9.0 importlib-resources-5.4.0 ipykernel-5.5.6 ipython-7.30.1 ipython-genutils-0.2.0 jedi-0.18.1 jupyter-client-7.1.0 jupyter-core-4.9.1 matplotlib-inline-0.1.3 nest-asyncio-1.5.4 parso-0.8.3 pexpect-4.8.0 pickleshare-0.7.5 prompt-toolkit-3.0.24 ptyprocess-0.7.0 pyface-7.3.0 pygments-2.10.0 python-dateutil-2.8.2 pyzmq-22.3.0 six-1.16.0 tornado-6.1 traitlets-5.0.5 traits-6.3.2 traitsui-7.2.1 wcwidth-0.2.5 zipp-3.6.0
```

This run:
```
Successfully installed apptools-5.1.0 asttokens-2.0.5 backcall-0.2.0 black-21.12b0 click-8.0.3 configobj-5.0.6 decorator-5.1.1 entrypoints-0.3 envisage-6.1.0.dev1 executing-0.8.2 importlib-metadata-4.10.1 importlib-resources-5.4.0 ipykernel-5.5.6 ipython-8.0.1 ipython-genutils-0.2.0 jedi-0.18.1 jupyter-client-7.1.2 jupyter-core-4.9.1 matplotlib-inline-0.1.3 mypy-extensions-0.4.3 nest-asyncio-1.5.4 parso-0.8.3 pathspec-0.9.0 pexpect-4.8.0 pickleshare-0.7.5 platformdirs-2.4.1 prompt-toolkit-3.0.24 ptyprocess-0.7.0 pure-eval-0.2.2 pyface-7.3.0 pygments-2.11.2 python-dateutil-2.8.2 pyzmq-22.3.0 six-1.16.0 stack-data-0.1.4 tomli-1.2.3 tornado-6.1 traitlets-5.0.5 traits-6.3.2 traitsui-7.2.1 typing-extensions-4.0.1 wcwidth-0.2.5 zipp-3.7.0
```

**Comment by mdickinson** [comment]
Updated the code to also check for the `IPython` version. IPython 8 is currently causing issues.

**Comment by mdickinson** [comment]
Sorry, @rahulporuri: I changed the code in this PR substantially after your review. (It turned out that the `IPython` version also needed to be considered.) A re-review would be welcome, but there's no urgency.

**Review by rahulporuri — APPROVED** [review]
Still LGTM

**Pull request merged**
