### PR TITLE
Add failing test and fix for old-style relative import.

### LINKED ISSUE #108: Old-style relative import ipython_kernel plugin
There's an old-style import here:

https://github.com/enthought/envisage/blob/7cb070da77d79aa37e132a3d44e55c3e593f627f/envisage/plugins/ipython_kernel/api.py#L1

Apparently this isn't being picked up by the tests, so we need a fix and a regression test.

### PR DESCRIPTION
**Pull request by mdickinson**
Creating a PR containing just a failing test (for #108). If this PR doesn't fail (initially) then we've got bigger problems.

Fixes #108.

### CODE REVIEW

**Comment by mdickinson** [comment]
It's failing, but for the wrong reasons.

Yep, we've got bigger problems.

**Comment by jwiggins** [comment]
😱

**Comment by mdickinson** [comment]
Okay, CI is now fixed, but is no longer running IPython-related tests (#113). Closing this PR for now: it's not useful to have it open while the IPython-related stuff is fixed.

**Comment by jwiggins** [comment]
This is the correct failure now, right?

**Comment by mdickinson** [comment]
PR reopened; test failing as expected. Now we can fix it!

**Comment by jwiggins** [comment]
Voilà!

**Comment by mdickinson** [comment]
@jwiggins Since you're watching this, care to do a quick review?

**Comment by jwiggins** [comment]
Yup. LGMT

**Comment by mdickinson** [comment]
Thanks!

**Pull request merged**
